
import type { Metadata } from "next";
import { Inter, Atkinson_Hyperlegible } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"], display : 'swap' });
const atkinson = Atkinson_Hyperlegible({weight : ["400", "700"], subsets : ['latin']})

export const metadata: Metadata = {
  title: "Cissy's Hair",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={atkinson.className}>
		      <Header/>
          {children}
		      <Footer/>
        </body>
    </html>
  );
}
